### ISSUE TITLE
What parts are safely modifiable?

### ISSUE THREAD

**Issue by inquisitiv3** [polyformproject/polyform-licenses#10]
As a legal layman I would like to know what parts of the license I could safely modify -- if I'm permitted to -- without having unintentional "side effects." Reading through the draft, one part I think that people maybe would like to change the number of employees or the amount of revenue in the SB license. Is there anything special with 100 employees and 1,000,000 USD, or did you decide on the numbers arbitrary?

**Comment by kemitchell** [comment]
I think there are at least two questions here. One about changing the terms. One about the numbers in Small Business.

I'll go ahead and try to answer the more general question about changes. If you're interested in Small Business specifically, please feel free to open another issue, and to look at #8.

I don't expect that we'll publish any kind of guide to modifying Polyform's terms.

Since license terms get interpreted based on everything within the text, it's very hard to say that one piece of language won't affect another. Specific or extreme values even for specific figures, like the headcount and revenue figures you pointed out, could lead to issues.

Moreover, the main thrust of Polyform is standardization. Standardization of license terms almost always means foregoing some custom tailoring, and the precise fit it offers, in exchange for using terms that others recognize. Our first priority will be encouraging standardization, not encouraging others to use our texts as starting points for scores of nonstandard variations.
