### ISSUE TITLE
Should patent defence have a 2 letter code?

### ISSUE THREAD

**Issue by paulberg** [polyformproject/polyform-licenses#22]
Although personally I am very in favor of this clause, when negotiating license terms this is often one of the clauses a party finds objectionable. Making this clause modular for easy removal may have use cases.

**Comment by kemitchell** [comment]
@paulberg why do counterparties resist those terms, in your experience?

**Comment by paulberg** [comment]
I often find myself negotiating to a licensee that has limited decision making potential (a technology transfer department at a government laboratory or university for instance) and has a strict policy in place that any patent revocation is unacceptable. For instance, the government contract they are under forbids this outright in order to protect its investment. Unfortunately this sometimes encompasses retaliatory clauses. This can get even trickier with licenses allowing modification since the licensee may fear that another licensee may incorporate their patents into the work without licensing them and they would wish to stop this but will be unable to do so without losing the right to use the software themselves.

**Comment by kemitchell** [comment]
@heathermeeker what do you think about dropping defensive termination here, as we did in Blue Oak?

**Comment by heathermeeker** [comment]
For the most part is seems OK, e.g. for a user who does not have a business or who does not use the software for production use.  But I was already concerned that universities could make unlimited use of the software because they are non-profit, even though they engage in a lot of profit making activity.  Unfortunately they are also big patent trolls. Removing defensive termination would unfairly favor them.

**Comment by paulberg** [comment]
How about a statement in the readme that removing the revocation section will not cause the base license to become inconsistent, but keep the clause in the base license.

I agree that the statement should be there by default and a fear is that if it is an optional add on then it may get left out more often then it should. I think optional removal is a better path, but it does complicate the semantics of the premise of having a base license with only additions.

**Comment by kemitchell** [comment]
@paulberg we've just landed #43, which adds a public license for the license terms themselves. They permit creating a variant without Patent Defense, provided Polyform branding and polyformproject.org get scrubbed from the text.

I'm not sure that Polyform itself will publish and standardize variants without Patent Defense. Not because there aren't real uses cases for them, but because we face a real combinatoric explosion with all the potentially optional sections we have.

The project's posture on license diversity may change in time, if it's successful in establishing at least some variants as standard. I'm honestly not sure how far out certainty there is likely to be.

I'm going to close for now. But please don't consider the matter settled for all time, and feel free to broach again in the future.
