### ISSUE TITLE
Terminate workers' licenses for companies' misdeeds?

### ISSUE THREAD

**Issue by kemitchell** [polyformproject/polyform-licenses#3]
As of 539af8a06be7bf42fe54787e71a31152708fc5ef, Patent Defense reads:

> If you or your company makes any written claim alleging that the software infringes or contributes to infringement of a patent, your patent license granted under these terms ends immediately.

I could read this to terminate individuals' patent licenses when their employers or clients bring patent claims, and not just their licenses to use on behalf of their employers or companies.

**Comment by lindenksv** [comment]
It should say "your company make."

I don't think this is an issue with employees. If you are using on behalf of your company, then really it's the company that enters into the license and the license to the company that terminates. If you, as an employees, want to use the software for a personal project, I don't think anyone could argue that you can't.

Clients is a little stickier. I would say that since the licenses aren't sublicensable and only apply to a family of affiliated companies, then if a company hires a contractor, who then pulls in polyform code, it's technically the company that agrees to the license since there is no mechanism for the contractor to sublicense polyform to the company. So they have their own contract with the copyright holder. And if that's the case, then termination of company's license doesn't affect contractor.

**Comment by kemitchell** [comment]
> It should say "your company make."

I believe this is addressed in #41, which also tries to make something like the distinction you do.
