### ISSUE TITLE
Require preservation of licensor identification and contact information

### ISSUE THREAD

**Issue by heathermeeker** [polyformproject/polyform-licenses#36]
I suggest we include a name or contact information for the licensor in the license.  Because limited licenses implicitly invite negotiation of alternative terms, licensees should know where to seek them.

**Comment by kemitchell** [comment]
I'd strongly prefer a fixed-form license, rather than a template.

Perhaps expand Notices to require preserving a notice somewhere outside the license text?

**Comment by heathermeeker** [comment]
I think this request is consistent with a fixed form license.  It would have a licensor copyright notice and also contact information.

**Comment by kemitchell** [comment]
I'd like to avoid including fill-in-the-blanks, like MIT or BSD. First because I think it complicates automation, on both licensor and licensee sides. Second because it invites tinkering and tweaking, which leads to MIT and BSD "family" problems. Last because I think having a specific company name right at the top reinforced the impression that it's a company- or application-specific form, which is the opposite of neutral standardization.

Apache-2.0-style `NOTICE` is still a gotcha. Creative Commons-style "retain the following if it is supplied by the Licensor with the Licensed Material" feels loose, but seems to work.

@heathermeeker, perhaps we could employ some of the thinking we and others have been doing around "credit" and attribution in other contexts? Could we define a ["magic number"](https://en.wikipedia.org/wiki/Magic_number_(programming)), perhaps a string like "Licensor Notice:", to make automatic detection and reproduction of the required notice automatic?

**Comment by heathermeeker** [comment]
I thought you had said before that you wanted to use the baked in copyright notice "feature" of BSD/MIT, so apologies as I clearly misunderstood (LOL I actually use the word "template" to mean the opposite.).   I like the idea of something automated, but that might be more of a suggestion than a requirement.

**Comment by kemitchell** [comment]
If you'd like to ensure that licensor ID and contact info travel with copies of the software, let's bake that into Notice. I think I can pull a PR together in an hour or so.

**Comment by heathermeeker** [comment]
Thank you
