### ISSUE TITLE
Any noncommercial purpose is a permitted purpose.

### ISSUE THREAD

**Issue by nothingismagick** [polyformproject/polyform-licenses#7]
I am reminded of the [attempts previous](https://web.cs.ucdavis.edu/~rogaway/ocb/license2.pdf) to limit usage to non-military purposes. In the wake of many legally legitimate but morally bankrupt noncommercial enterprises, I wonder if the language here is enough or if there could be another clause that limits particular industries from using the software.

**Comment by kemitchell** [comment]
@nothingismagick there have been several "ethical licenses" over the years. Folks often mention JSON, HESSLA, and depending on how they see it, the Peer Production License. Recently, we've seen "anti-Nazi" and anti-ICE licenses. Now 996.ICU, too.

I don't think Polyform is currently heading toward publishing explicitly ethics-driven license terms. Rather, we're exploring territory analogous to Creative Commons' [NonCommercial](https://creativecommons.org/licenses/by-nc/4.0/) forms, but for software. Some folks may find they can use noncommercial terms to address their ethical concerns indirectly. But they might be better served writing their ethical concerns out in the terms explicitly.

To be clear, I don't think Polyform is going to take up that project for them, but that's not because Polyform as a whole or any of the people participating in it oppose. I've [written out some pointers](https://writing.kemitchell.com/2019/03/15/Ethical-Subcommons.html) precisely for folks looking to express their ethics through terms. I'm involved in some [other drafting projects](http://github.com/kemitchell/icepick) trying to express new or evolved ethical codes in legal terms.

**Comment by nothingismagick** [comment]
Thanks for the commentary. I was careful not to align myself to any terms regarding capitalism, and perhaps I should have also avoided the word "ethics" because of its polarizing nature. Nevertheless, there are some types of business that an author might not want to have their work associated with, such as for-profit capitalization of third party work - which CC-NC-ND seeks to circumvent.

I totally appreciate where you are going with this topic, and your very neutral stance is probably a moral imperative for this type of rights allocation (as opposed to the approach taken with icepick) - nevertheless I think there is still some wiggle-room here. No?

**Comment by kemitchell** [comment]
@nothingismagick I should ask you: What would you like to see Polyform offer that isn't in the current draft language?

**Comment by nothingismagick** [comment]
I loved this article and the wonderfully intellectual click-baity title: https://writing.kemitchell.com/2019/05/08/Tyranny-of-Permissionlessness.html - and I was wishing for 

I am involved in the discussions going on over at the SFOSC (such as this one https://github.com/sfosc/sfosc/issues/84) and one of the things we are looking at is finding a type of self-definition toward a model of sustainability. I wish there were a way to define this in a license. Maybe Polyform isn't the right one, but I think the direction is good...
